### ISSUE TITLE
Module depends on puppet-staging, which doesn't exist

### ISSUE THREAD

**Issue by stefanlasiewski** [danofthewired/puppet-bitbucket#1]
The page at https://forge.puppetlabs.com/thewired/bitbucket/dependencies lists the following dependency:

    puppet/staging (>= 1.0.0)

However, that hyperlink points to a page which is a 404:

```
$ curl --head https://forge.puppetlabs.com/puppet/staging
HTTP/1.1 404 Not Found
Server: nginx
Date: Wed, 23 Dec 2015 00:40:39 GMT
```
In addition, the Puppet module command fails. Has the puppet/staging module been renamed?

```
$ puppet module install puppet-staging
Notice: Preparing to install into .../modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install 'puppet-staging' (latest)
  No releases are available from https://forgeapi.puppetlabs.com
    Does 'puppet-staging' have at least one published release?
```

**Comment by stefanlasiewski** [comment]
It looks like nanliu picked up this community-maintained module?

https://forge.puppetlabs.com/nanliu/staging

**Comment by waza-ari** [comment]
As far as I can tell, at least now, the puppet/staging module is alive: https://forge.puppet.com/puppet/staging

It is already required by another module I use, which causes a name conflict and I cannot use this module. Any chance to revert this change?
