### ISSUE TITLE
Backup client download url

### ISSUE THREAD

**Issue by elisiano** [danofthewired/puppet-bitbucket#11]
Recently the url of the backup client changed ( https://github.com/danofthewired/puppet-bitbucket/blob/master/manifests/backup.pp#L47 ) to reflect changes on the marketplace.

Forcing the ${version} in the download URL though, breaks installation on premises where users mirror the archives to a local server. Would it make sense to add "/${version}" to the default value of $backupclient_url in init.pp instead? (so that end users can override this)

**Comment by danofthewired** [comment]
Sorry about that, Atlasssian keeps moving around there backup client location. I use an Artifactory Server to manage by installation binaries so just adjusted my path to include the version. The version is required for those connecting directly to the Internet and would work without any further class overrides. I'll look into creating some sort of override for this.

**Comment by elisiano** [comment]
Closing this issue as it's no longer relevant for me. Feel free to reopen if you want to keep it as a to-do.
