### ISSUE TITLE
Unzip not present on centos 7

### ISSUE THREAD

**Issue by npwalker** [danofthewired/puppet-bitbucket#14]
Using the module to install bitbucket server 4.4.1 on centos 7 I get the following.  

```
Error: Execution of 'unzip -o /tmp/bitbucket-backup-distribution-2.0.2.zip' returned 1:
Error: /Stage[main]/Bitbucket::Backup/Archive[/tmp/bitbucket-backup-distribution-2.0.2.zip]/creates: change from archive not extracted to extracting in /opt/bitbucket-backup to create /opt/bitbucket-backup/bitbucket-backup-client-2.0.2/lib failed: Execution of 'unzip -o /tmp/bitbucket-backup-distribution-2.0.2.zip' returned 1:
```

Of course I can resolve the issue by installing unzip on the system but it seems that the module should ensure that unzip is present if it is going to be used.

**Comment by danofthewired** [comment]
Thanks for the info. Seeing it's the archive module performing the unzip you can raise an issue with that module https://forge.puppetlabs.com/puppet/archive. I actually have the same issues at times and use a role/profiles pattern where I just have a profile for bitbucket which makes sure the unzip package is present before I execute the bitbucket module.

**Comment by stefanlasiewski** [comment]
I ran into this on CentOS 6. 

Echoing Dan's comments, this is a big in puppet-archive. The specific bug is here:

https://github.com/voxpupuli/puppet-archive/issues/154
