### ISSUE TITLE
archive class missing?

### ISSUE THREAD

**Issue by jeski** [danofthewired/puppet-bitbucket#16]
Hi, was looking at this module for possible use and noticed that in the install.pp you're including ::archive, which doesn't exist.

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by danofthewired** [comment]
Hi, ::archive is a dependent puppet module that this module requires. You can find the archive module here https://forge.puppetlabs.com/puppet/archive. Please review the dependecincies for this module here https://forge.puppetlabs.com/thewired/bitbucket/dependencies as there are a few other modules which you may also require.
