### ISSUE TITLE
Proxy settings changed >5.3.x

### ISSUE THREAD

**Issue by xJARiD** [danofthewired/puppet-bitbucket#48]
proxyName, proxyPort, secure and scheme have been moved to bitbucket.properties.

They are now referenced as:
server.scheme
server.proxy-port
server.proxy-name
server.secure

https://confluence.atlassian.com/bitbucketserver/migrate-server-xml-customizations-to-bitbucket-properties-897811761.html#id-_MigrateServerXML-migrationexamples

Workaround for now: Rename proxy settings in bitbucket.properties.

**Comment by danofthewired** [comment]
Hi, this has already been accounted for when I released a version which supported Bitbucket 5+. You just need to alter your proxy hiera/class param definition. Don't use the below example for Bitbucket 4 or earlier as the server.xml is still used and the examples in the module will still work.

An example in hiera: 
bitbucket::proxy: 
  server.scheme:     'http' 
  server.proxy-name:  bitbucket.myorg.au' 
  server.proxy-port:  '80' 
  server.secure: true

In theory you could add any bitbucket.properties setting using this structure as the module doesn't validate if the entry is proxy related.

**Comment by xJARiD** [comment]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Syntax error at 'proxy-name'

I get same for proxy-port, scheme and secure...

**Comment by xJARiD** [comment]
My bad!
Using class param, I had to put ' ' either side 👍 

proxy                => {
      'server.scheme'     => 'https',
      'server.proxy-name' => 'bitbucket.example.com',
      'server.proxy-port' => '443',
    },
