### ISSUE TITLE
Clean up JIRA cruft

### ISSUE THREAD

**Issue by decibelhertz** [danofthewired/puppet-bitbucket#51]
Thanks for this module.  I tried to use _puppet-stash_ to spin up a modern BitBucket instance and hit a hard coded problem that made me find this module, which worked readily.

Two questions:

1. Would you consider updating the issue I mentioned in https://github.com/voxpupuli/puppet-stash/issues/151 ? In short, https://github.com/danofthewired/puppet-bitbucket/blob/master/manifests/service.pp#L29 needs to have a module-specific name, such as `bitbucket_refresh_systemd`. If we want to stand a chance of using this module of the same node that is running _puppet-jira_
2. Can we please update the _Description_ at https://github.com/danofthewired/puppet-bitbucket/blob/master/templates/bitbucket.service.erb#L2 ? We are definitely not running JIRA.

I can do a PR if you like.  These are such minor hacks, wasn't sure it was worth that.

Cheers.

**Comment by danofthewired** [comment]
Hi, I made the updates and published a new release on PuppetForge.

**Comment by decibelhertz** [comment]
2.2.3 working great.  Thanks much.
