### ISSUE TITLE
JRE_HOME and JAVA_HOME not set automatically in 5.6.X

### ISSUE THREAD

**Issue by djermann** [danofthewired/puppet-bitbucket#53]
I tried installing Bitbucket version 5.6.2 but the JAVA_HOME and JRE_HOME did not get set automatically. I had to set them manually in bin/set-jre-home.sh.

**Comment by danofthewired** [comment]
Hi,
Did you set the javahome in your class or hiera definition? I don't actually manage set-jre-home.sh within this module, the JAVA_HOME is added to other scripts including the service init, start_webapp and setenv.sh as long as the javahome class parameter exists.

**Comment by djermann** [comment]
Hi,
I set it only in hiera. It worked for an older version (4.9.1) but when i upgraded to 5.6.2, Bitbucket did not start automatically because the JAVA_HOME was not set. I think setenv.sh was removed an replaced by other files in newer versions of Bitbucket.

**Comment by danofthewired** [comment]
Hi, I did make a change with Bitbucket 5.0.0 as setenv.sh was replaced with _start-webapp.sh. The  config.pp manifest handles this logic. I have tested this and it seems to work fine in my RHEL6 installation. Can you check that your _start-webapp.sh is updated with the JAVA_HOME in /bin within your Bitbucket installation. Also what Linux dist are you using?

**Comment by djermann** [comment]
I am using Debian 9. Strangely, I can not reproduce this problem again. Now the JAVA_HOME variable get's set in _start-webapp.sh, so it looks fine. I did not check this file when this problem first came up, so I can not tell if JAVA_HOME did get updated. But now after fully removing Bitbucket and installing it again, it works. Anyway, thank you very much for your help!
