### ISSUE TITLE
Backup client installation fails

### ISSUE THREAD

**Issue by djermann** [danofthewired/puppet-bitbucket#54]
When I try to install the backup client with this module I get following error messages:

Error: Execution of 'unzip -o /tmp/bitbucket-backup-distribution-3.2.0.zip' returned 1: 
Error: /Stage[main]/Bitbucket::Backup/Archive[/tmp/bitbucket-backup-distribution-3.2.0.zip]/ensure: change from absent to present failed: Execution of 'unzip -o /tmp/bitbucket-backup-distribution-3.2.0.zip' returned 1:

**Comment by djermann** [comment]
I found the problem. Unzip was not installed on the server by default. 
If would be helpful if you could document that.

**Comment by danofthewired** [comment]
Hi,

Yes, there is a dependency that unzip is installed however this is more to do with the puppet/archive module. If you look at the README of this module it states that responsibility of archive dependencies tar,gunzip etc etc is upto the user, refer to https://github.com/voxpupuli/puppet-archive/issues/291.

However, it's a good call to add some documentation to mention this as it's the 2nd time I've answered this question. I'll add this to my README.

Thanks

**Comment by djermann** [comment]
Thank you very much!
Therefore I'll close this Issue.
