### ISSUE TITLE
Unable to add the '--no-search' flag

### ISSUE THREAD

**Issue by kassovix** [danofthewired/puppet-bitbucket#57]
I use your module to install Bitbucket Datacenter.
I want to disable the embedded Elastic Search, with the start option `--no-search` as described here : https://confluence.atlassian.com/bitbucketserver/install-and-configure-a-remote-elasticsearch-instance-815577748.html

How can I add this option with the Puppet module ?

**Comment by danofthewired** [comment]
The module currently doesn't support this option.

This would need to be added as a additional hiera variable and included in the Puppet templates for the bitbucket service. Either a flag to determine if Datacenter is the installation option via a "if" statement or just an additional hiera variable to pass in the "--no-search" flag (or any other future flag) default would be empty.

**Comment by kassovix** [comment]
Thank you for your response.
I'll try to make a PR for that.

**Comment by danofthewired** [comment]
Resolved by #58
