### ISSUE TITLE
Zipped Directory Name does not follow Puppetforge packaging Requirements

### ISSUE THREAD

**Issue by Conzar** [danofthewired/puppet-bitbucket#62]
The uploaded zip files for this project contains a directory with a name that doesn't match the zipped filename.  This causes issue with r10k/g10k like tools.
![image](https://user-images.githubusercontent.com/2646975/41387955-c96eba8a-6fdd-11e8-8ec9-8ffd6e726ded.png)

For thewired-bitbucket-2.2.7.tar.gz the contained directory name should be
thewired-bitbucket-2.2.7

**Comment by danofthewired** [comment]
Released a new version and updated the naming within the archive file.

**Comment by Conzar** [comment]
Thank you!
