### ISSUE TITLE
Support for Bitbucket 6.x

### ISSUE THREAD

**Issue by fabiogermann** [danofthewired/puppet-bitbucket#64]
The current version should be compatible with the version 6 of bitbucket.

**Comment by mojibake-umd** [comment]
I was able to get 6.3.0 by setting the following in Hiera.
bitbucket::download_url: 'https://product-downloads.atlassian.com/software/stash/downloads'
Do not know if it works for any other 6.x, as I was only looking to upgrade from 5.14.0 to the latest.
Also do not know if older versions are available at that new download_url.
If I have time I will see if I can make a pull request.

**Comment by mojibake-umd** [comment]
Actually the updated default download_url is in a commit https://github.com/danofthewired/puppet-bitbucket/commit/cd8408799e40e5f63807f33150a020d3af40494b on feature branch 'backup-improvements' in addition to "Bitbucket 6 support". I have not experienced any issues with module version 2.2.8 installing and running Bitbucket 6.3.0

**Comment by danofthewired** [comment]
Module now supports Bitbucket 6 and 7.
